# Generated by Django 5.1.3 on 2024-11-23 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('evaluation_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('evaluation_type', models.CharField(choices=[('EXAM', 'Prova'), ('ASSIGNMENT', 'Trabalho'), ('PARTICIPATION', 'Participação'), ('QUIZ', 'Quiz'), ('FINAL', 'Prova Final')], default='EXAM', max_length=15)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
            ],
        ),
    ]
